//
// Created by rzdv on 10.05.2026.
//

#ifndef EXTRACTSTRINGLITERALSFROMCCODE_TEST_UTILS_H
#define EXTRACTSTRINGLITERALSFROMCCODE_TEST_UTILS_H


class test_utils {
};


#endif //EXTRACTSTRINGLITERALSFROMCCODE_TEST_UTILS_H
